add_executable(integration_test_application_lifecycle test_application_lifecycle.cpp)
set_target_properties(integration_test_application_lifecycle PROPERTIES OUTPUT_NAME test_application_lifecycle)
target_link_libraries(integration_test_application_lifecycle PRIVATE nodus_vision_runtime GTest::gtest_main)
target_compile_features(integration_test_application_lifecycle PRIVATE cxx_std_17)
add_test(NAME integration_test_application_lifecycle COMMAND integration_test_application_lifecycle)
